# Configuration of app
name: test_app
url: http://www.example.com/test_app
master_app_url: http://www.example.com/master

test:
  article:
    url: http://www.example.com/article
    api:
      url:
        comment_list: comments/recent
development:
  article:
    url: http://www.example.com/article
    api:
      url:
        comments: articles/:article_id/comments
    database:
      adapter: mysql
      database: article_development
      username: root
      password: root
      host: localhost

# columns needed for readonly models in test
readonly_for_test:
  comments:
    string: title
