# Configuration of app
name: test_app
url: http://www.idapted.com/test_app
core_root: http://www.idapted.com/core

#options
#url: #url of app
#api: #api of this app

#mock settings for other app (basically used in development environment)
#development:
#  scenario:  #other app's name
#    url:
#    database:
#      adapter: mysql
#      encoding: utf8
#      database: lpr_development
#      host: localhost
#      user: root
#      password: root
#    other app's settings
test:
  article:
    url: http://www.idapted.com/article
    api:
      url:
        comment_list: comments/recent
development:
  article:
    url: http://www.idapted.com/article
    api:
      url:
        comments: articles/:article_id/comments
    database:
      adapter: mysql
      database: article_development
      username: root
      password: root
      host: localhost

# columns needed for readonly models in test
readonly_for_test:
  comments:
    string: title
